- hosts: all
  handlers: 
  - name: Restart and enable RedHat
    systemd:
      name: httpd
      state: restarted
      enabled: yes
    when: ansible_os_family == "RedHat"
  - name: restart and enable Debian
    systemd:
      name: apache2
      state: restarted
      enabled: yes
    when: ansible_os_family == "Debian"
  tasks:
  - yum:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"
    notify: Restart and enable RedHat
  - apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    notify: restart and enable Debian